server:
  port: 7050
spring:
  application:
    name: authenticationserver
  cloud:
    nacos:
      discovery:
        server-addr:  http://127.0.0.1:8850 # nacos服务器的地址
    openfeign:
      httpclient:
        enabled: true