server:
  port: 7050
spring:
  application:
    name: authentication-server
  cloud:
    nacos:
      discovery:
        server-addr:  http://127.0.0.1:8850 # nacos服务器的地址
logging:
  level:
    com:
      wen:
        orderserver: DEBUG