server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/articles?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  application:
    name: sysadmin
  cloud:
    nacos:
      discovery:
        server-addr:  http://127.0.0.1:8850
mybatis:
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true